[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"
